# docker/Dockerfile.dev
FROM ubuntu:24.04

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    cmake \
    git \
    pkg-config \
    libssl-dev \
    entr \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY src/ /app/src/
COPY CMakeLists.txt /app
COPY resources/ /app/resources/
COPY externals/ /app/externals/
COPY dev.sh /app/dev.sh

RUN chmod +x /app/dev.sh

EXPOSE 8000
